### ISSUE TITLE
Competition model : not able to repeat simulation steps

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#33] opened 2020-04-19 12:08 UTC
Hi Tanguy,

I'm at last playing with the critical resources models. Namely growth cone model  `res_po_rt`.

I am facing the issue that the model runs ony over one simulation step. If you launch a second simulation step after a first one, it remains stucked.

i.e. 
`> ds.simulate(12000 * minute)`
works, but not
```
> ds.simulate(6000 * minute)
> ds.simulate(6000 * minute)
```
See attached code. 

See you

Samuel

[res_po_rt_neuron_simple_simulation.zip](https://github.com/SENeC-Initiative/DeNSE/files/4498905/res_po_rt_neuron_simple_simulation.zip)

**Comment by Silmathoron** [comment] 2020-04-23 10:04
It seems that the issue comes from the VanPelt branching (parameters seem quite unreasonable but maybe the issue is more profound, investigating)
@aquaresima did you make progress on the new implementation?

**Comment by Silmathoron** [comment] 2020-04-27 06:13
The issue actually came from an integer resolution that was not checked.
Fixed by #38

**Closed by Silmathoron** 2020-04-27 06:13 UTC
Labels: bug
